// Package main предоставляет инструмент для автоматической генерации методов Reset()
// для структур с директивой // generate:reset, а также обобщенный пул объектов.
//
// Инструмент рекурсивно обходит директории, находит структуры с комментарием
// generate:reset и генерирует для них метод Reset(), который обнуляет все поля
// до значений по умолчанию.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"text/template"
)

// resetFileTmpl - шаблон для генерации файла reset.gen.go.
// Содержит предупреждение о том, что файл сгенерирован автоматически,
// и список всех методов Reset для структур в пакете.
var resetFileTmpl = template.Must(template.New("reset").Parse(`// Code generated by cmd/reset
// DO NOT EDIT.

package {{.PkgName}}

{{range .Resets}}{{.}}
{{end}}
`))

// resetMethodTmpl - шаблон для генерации метода Reset для конкретной структуры.
// Включает проверку на nil для получателя (если указатель) и обнуление каждого поля.
var resetMethodTmpl = template.Must(template.New("reset").Parse(`func ({{.Recv}} *{{.StructName}}) Reset() {
	{{- if .Recv}}if {{.Recv}} == nil { return }{{end}}
	
	{{range .Fields}}
	{{.}}
	{{end}}
}
`))

// main - точка входа в генератор кода.
//
// Параметры командной строки:
//
//	-root string: корневая директория для поиска (по умолчанию ".")
//	-dry-run bool: если true, выводит сгенерированный код без записи в файлы
//
// Пример использования:
//
//	go run cmd/reset/main.go -root ./pkg -dry-run
//	go run cmd/reset/main.go -root .
func main() {
	root := flag.String("root", ".", "root directory")
	dryRun := flag.Bool("dry-run", false, "dry run")
	flag.Parse()

	log.SetFlags(0)
	if err := filepath.WalkDir(*root, func(path string, d fs.DirEntry, err error) error {
		if err != nil || !d.IsDir() || strings.Contains(path, "vendor") || strings.Contains(path, "cmd") {
			return nil
		}
		return generatePackage(path, *dryRun)
	}); err != nil {
		log.Fatal(err)
	}
}

// generatePackage генерирует файл reset.gen.go для указанной директории.
//
// Параметры:
//   - dir: путь к директории с Go пакетом
//   - dryRun: если true, только выводит код в stdout без записи файла
//
// Возвращает:
//   - error: ошибка генерации или записи файла
//
// Алгоритм:
//  1. Парсит все .go файлы в директории
//  2. Находит структуры с комментарием // generate:reset
//  3. Генерирует методы Reset для каждой структуры
//  4. Форматирует код через go fmt
//  5. Записывает результат в reset.gen.go (или выводит при dry-run)
func generatePackage(dir string, dryRun bool) error {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		return nil // игнорируем ошибки парсинга
	}

	pkgName, resets := getPackageInfo(pkgs)
	if len(resets) == 0 {
		return nil
	}

	var buf bytes.Buffer
	if err := resetFileTmpl.Execute(&buf, struct {
		PkgName string
		Resets  []string
	}{
		PkgName: pkgName,
		Resets:  resets,
	}); err != nil {
		return err
	}

	code := buf.String()
	fileName := filepath.Join(dir, "reset.gen.go")

	if dryRun {
		fmt.Printf("\n🟢 %s\n%s\n", fileName, code)
		return nil
	}

	formatted, err := format.Source([]byte(code))
	if err != nil {
		return err
	}
	return os.WriteFile(fileName, formatted, 0644)
}

// getPackageInfo извлекает информацию о пакете и генерирует методы Reset.
//
// Параметры:
//   - pkgs: карта разобранных пакетов из parser.ParseDir
//
// Возвращает:
//   - string: имя пакета
//   - []string: список сгенерированных методов Reset
//
// Поиск структур:
//   - Ищет объявления типов (type ... struct)
//   - Проверяет наличие комментария // generate:reset
//   - Для каждой найденной структуры генерирует метод Reset
func getPackageInfo(pkgs map[string]*ast.Package) (string, []string) {
	if len(pkgs) == 0 {
		return "", nil
	}

	// Берем первое имя пакета (в директории должен быть один пакет)
	pkgName := ""
	for name := range pkgs {
		pkgName = name
		break
	}

	var resets []string
	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			ast.Inspect(file, func(n ast.Node) bool {
				d, ok := n.(*ast.GenDecl)
				if !ok || d.Tok != token.TYPE || !hasGenerateReset(d.Doc) {
					return true
				}

				for _, spec := range d.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}

					st, ok := ts.Type.(*ast.StructType)
					if !ok {
						continue
					}

					resetCode, err := generateResetMethod(pkgName, ts.Name.Name, st.Fields)
					if err != nil {
						continue
					}
					resets = append(resets, resetCode)
				}
				return true
			})
		}
	}

	return pkgName, resets
}

// generateResetMethod генерирует код метода Reset для структуры.
//
// Параметры:
//   - pkgName: имя пакета (не используется в текущей реализации)
//   - structName: имя структуры
//   - fields: список полей структуры
//
// Возвращает:
//   - string: сгенерированный код метода Reset
//   - error: ошибка выполнения шаблона
//
// Сгенерированный метод:
//   - Проверяет получатель на nil (если указатель)
//   - Обнуляет каждое поле в соответствии с его типом
func generateResetMethod(pkgName, structName string, fields *ast.FieldList) (string, error) {
	recv := strings.ToLower(structName[:1])
	fieldResets := make([]string, 0)

	if fields != nil {
		for _, f := range fields.List {
			if len(f.Names) == 0 || f.Type == nil {
				continue
			}
			reset := resetField(recv, f.Names[0].Name, typeString(f.Type))
			fieldResets = append(fieldResets, fmt.Sprintf("%s.%s = %s", recv, f.Names[0].Name, reset))
		}
	}

	var buf bytes.Buffer
	err := resetMethodTmpl.Execute(&buf, struct {
		Recv       string
		StructName string
		Fields     []string
	}{
		Recv:       recv,
		StructName: structName,
		Fields:     fieldResets,
	})
	return buf.String(), err
}

// hasGenerateReset проверяет наличие директивы // generate:reset в комментарии.
//
// Параметры:
//   - doc: группа комментариев перед объявлением
//
// Возвращает:
//   - bool: true если найден комментарий с generate:reset
//
// Пример:
//
//	// generate:reset
//	type User struct { ... }
func hasGenerateReset(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		if strings.Contains(c.Text, "generate:reset") {
			return true
		}
	}
	return false
}

// typeString преобразует AST выражение типа в строковое представление.
//
// Параметры:
//   - t: AST узел типа
//
// Возвращает:
//   - string: строковое представление типа
//
// Поддерживаемые типы:
//   - Идентификаторы (int, string, bool)
//   - Указатели (*T)
//   - Массивы/слайсы ([]T)
//   - Карты (map[K]V)
//   - Селекторы (pkg.Type)
func typeString(t ast.Expr) string {
	switch v := t.(type) {
	case *ast.Ident:
		return v.Name
	case *ast.StarExpr:
		return "*" + typeString(v.X)
	case *ast.ArrayType:
		return "[]" + typeString(v.Elt)
	case *ast.MapType:
		return "map[" + typeString(v.Key) + "]" + typeString(v.Value)
	case *ast.SelectorExpr:
		return typeString(v.X) + "." + v.Sel.Name
	}
	return "unknown"
}

// resetField возвращает значение по умолчанию для поля указанного типа.
//
// Параметры:
//   - recv: имя переменной-получателя (например, "u" для user)
//   - name: имя поля
//   - tp: строковое представление типа
//
// Возвращает:
//   - string: выражение для обнуления поля
//
// Правила обнуления:
//   - Числовые типы: 0
//   - string: ""
//   - slice: slice[:0] (очистка с сохранением容量)
//   - map: nil
//   - указатели: nil
//   - bool: false
//   - другие типы: nil
func resetField(recv, name, tp string) string {
	switch {
	case strings.HasPrefix(tp, "int") || strings.HasPrefix(tp, "uint") || strings.HasPrefix(tp, "float"):
		return "0"
	case tp == "string":
		return `""`
	case strings.HasPrefix(tp, "[]"):
		return recv + "." + name + "[:0]"
	case strings.HasPrefix(tp, "map["):
		return "nil"
	case strings.HasPrefix(tp, "*"):
		return "nil"
	case tp == "bool":
		return "false"
	default:
		return "nil"
	}
}

// Resetter - интерфейс для объектов, которые могут быть сброшены в初始 состояние.
//
// Используется в Pool для автоматического сброса объектов перед возвратом в пул.
type Resetter interface {
	Reset()
}

// Pool - обобщенный пул объектов с поддержкой сброса состояния.
//
// Pool позволяет переиспользовать объекты для снижения нагрузки на GC.
// Все объекты должны реализовывать интерфейс Resetter.
//
// Типовые параметры:
//   - T: тип объектов в пуле, должен реализовывать Resetter
//
// Пример использования:
//
//	type User struct {
//	    Name string
//	    Age  int
//	}
//
//	// generate:reset
//	type User struct { ... } // автоматически генерируется Reset()
//
//	pool := New[User]()
//	user := pool.Get()
//	user.Name = "John"
//	pool.Put(user) // автоматически вызывает user.Reset()
type Pool[T Resetter] struct {
	pool sync.Pool
}

// New создает новый пул объектов.
//
// Возвращает:
//   - *Pool[T]: новый пул для объектов типа T
//
// Пример:
//
//	pool := New[User]()
func New[T Resetter]() *Pool[T] {
	return &Pool[T]{}
}

// Get возвращает объект из пула.
//
// Если в пуле есть объект, он извлекается и возвращается.
// Если пул пуст, создается новый объект через new(T).
//
// Возвращает:
//   - *T: указатель на объект (никогда не nil)
//
// Пример:
//
//	user := pool.Get()
//	defer pool.Put(user)
func (p *Pool[T]) Get() *T {
	if obj := p.pool.Get(); obj != nil {
		return obj.(*T)
	}
	return new(T)
}

// Put возвращает объект в пул.
//
// Перед возвратом автоматически вызывается метод Reset() объекта.
// После вызова Put объект не должен использоваться.
//
// Параметры:
//   - obj: объект для возврата в пул
//
// Пример:
//
//	user := pool.Get()
//	user.Name = "John"
//	pool.Put(user) // user.Reset() вызывается автоматически
func (p *Pool[T]) Put(obj T) {
	obj.Reset()
	p.pool.Put(obj)
}
