package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	root := flag.String("root", ".", "root directory")
	dryRun := flag.Bool("dry-run", false, "dry run")
	flag.Parse()

	log.SetFlags(0)
	if err := filepath.WalkDir(*root, func(path string, d fs.DirEntry, err error) error {
		if err != nil || !d.IsDir() || strings.Contains(path, "vendor") || strings.Contains(path, "cmd") {
			return nil
		}
		return generatePackage(path, *dryRun)
	}); err != nil {
		log.Fatal(err)
	}
}

func generatePackage(dir string, dryRun bool) error {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		return nil
	}

	var resets []string
	pkgName := ""

	for name := range pkgs {
		pkgName = name
		break
	}

	// Reset методы
	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			ast.Inspect(file, func(n ast.Node) bool {
				if d, ok := n.(*ast.GenDecl); ok && d.Tok == token.TYPE && hasGenerateReset(d.Doc) {
					for _, spec := range d.Specs {
						if ts, ok := spec.(*ast.TypeSpec); ok {
							if st, ok := ts.Type.(*ast.StructType); ok {
								resets = append(resets, genReset(pkgName, ts.Name.Name, st.Fields))
							}
						}
					}
				}
				return true
			})
		}
	}

	if len(resets) == 0 {
		return nil
	}

	code := fmt.Sprintf("// Code generated by cmd/reset\npackage %s\n\n%s", pkgName, strings.Join(resets, "\n"))
	fileName := filepath.Join(dir, "reset.gen.go")

	if dryRun {
		fmt.Printf("\n🟢 %s\n%s\n", fileName, code)
		return nil
	}

	formatted, _ := format.Source([]byte(code))
	return os.WriteFile(fileName, formatted, 0644)
}

func hasGenerateReset(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		if strings.Contains(c.Text, "generate:reset") {
			return true
		}
	}
	return false
}

func genReset(pkgName, structName string, fields *ast.FieldList) string {
	var lines []string
	r := strings.ToLower(structName[:1])

	lines = append(lines,
		fmt.Sprintf("func (%s *%s) Reset() {", r, structName),
		fmt.Sprintf("\tif %s == nil { return }", r),
		"",
	)

	if fields != nil {
		for _, f := range fields.List {
			if len(f.Names) > 0 && f.Type != nil {
				reset := resetField(r, f.Names[0].Name, typeString(f.Type))
				lines = append(lines, fmt.Sprintf("\t%s.%s = %s", r, f.Names[0].Name, reset))
			}
		}
	}

	lines = append(lines, "}")
	return strings.Join(lines, "\n")
}

func typeString(t ast.Expr) string {
	switch v := t.(type) {
	case *ast.Ident:
		return v.Name
	case *ast.StarExpr:
		return "*" + typeString(v.X)
	case *ast.ArrayType:
		return "[]" + typeString(v.Elt)
	case *ast.MapType:
		return "map[" + typeString(v.Key) + "]" + typeString(v.Value)
	case *ast.SelectorExpr:
		return typeString(v.X) + "." + v.Sel.Name
	}
	return "unknown"
}

func resetField(recv, name, tp string) string {
	switch {
	case strings.HasPrefix(tp, "int") || strings.HasPrefix(tp, "uint") || strings.HasPrefix(tp, "float"):
		return "0"
	case tp == "string":
		return `""`
	case strings.HasPrefix(tp, "[]"):
		return recv + "." + name + "[:0]"
	case strings.HasPrefix(tp, "map["):
		return "nil"
	case strings.HasPrefix(tp, "*"):
		return "nil"
	case tp == "bool":
		return "false"
	default:
		return "nil"
	}
}
