package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"text/template"
)

var resetFileTmpl = template.Must(template.New("reset").Parse(`// Code generated by cmd/reset
// DO NOT EDIT.

package {{.PkgName}}

{{range .Resets}}{{.}}
{{end}}
`))

var resetMethodTmpl = template.Must(template.New("reset").Parse(`func ({{.Recv}} *{{.StructName}}) Reset() {
	{{- if .Recv}}if {{.Recv}} == nil { return }{{end}}
	
	{{range .Fields}}
	{{.}}
	{{end}}
}
`))

func main() {
	root := flag.String("root", ".", "root directory")
	dryRun := flag.Bool("dry-run", false, "dry run")
	flag.Parse()

	log.SetFlags(0)
	if err := filepath.WalkDir(*root, func(path string, d fs.DirEntry, err error) error {
		if err != nil || !d.IsDir() || strings.Contains(path, "vendor") || strings.Contains(path, "cmd") {
			return nil
		}
		return generatePackage(path, *dryRun)
	}); err != nil {
		log.Fatal(err)
	}
}

func generatePackage(dir string, dryRun bool) error {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		return nil
	}

	pkgName, resets := getPackageInfo(pkgs)
	if len(resets) == 0 {
		return nil
	}

	var buf bytes.Buffer
	if err := resetFileTmpl.Execute(&buf, struct {
		PkgName string
		Resets  []string
	}{
		PkgName: pkgName,
		Resets:  resets,
	}); err != nil {
		return err
	}

	code := buf.String()
	fileName := filepath.Join(dir, "reset.gen.go")

	if dryRun {
		fmt.Printf("\n🟢 %s\n%s\n", fileName, code)
		return nil
	}

	formatted, err := format.Source([]byte(code))
	if err != nil {
		return err
	}
	return os.WriteFile(fileName, formatted, 0644)
}

func getPackageInfo(pkgs map[string]*ast.Package) (string, []string) {
	if len(pkgs) == 0 {
		return "", nil
	}

	pkgName := ""
	for name := range pkgs {
		pkgName = name
		break
	}

	var resets []string
	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			ast.Inspect(file, func(n ast.Node) bool {
				d, ok := n.(*ast.GenDecl)
				if !ok || d.Tok != token.TYPE || !hasGenerateReset(d.Doc) {
					return true
				}

				for _, spec := range d.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}

					st, ok := ts.Type.(*ast.StructType)
					if !ok {
						continue
					}

					resetCode, err := generateResetMethod(pkgName, ts.Name.Name, st.Fields)
					if err != nil {
						continue
					}
					resets = append(resets, resetCode)
				}
				return true
			})
		}
	}

	return pkgName, resets
}

func generateResetMethod(pkgName, structName string, fields *ast.FieldList) (string, error) {
	recv := strings.ToLower(structName[:1])
	fieldResets := make([]string, 0)

	if fields != nil {
		for _, f := range fields.List {
			if len(f.Names) == 0 || f.Type == nil {
				continue
			}
			reset := resetField(recv, f.Names[0].Name, typeString(f.Type))
			fieldResets = append(fieldResets, fmt.Sprintf("%s.%s = %s", recv, f.Names[0].Name, reset))
		}
	}

	var buf bytes.Buffer
	err := resetMethodTmpl.Execute(&buf, struct {
		Recv       string
		StructName string
		Fields     []string
	}{
		Recv:       recv,
		StructName: structName,
		Fields:     fieldResets,
	})
	return buf.String(), err
}

func hasGenerateReset(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		if strings.Contains(c.Text, "generate:reset") {
			return true
		}
	}
	return false
}

func typeString(t ast.Expr) string {
	switch v := t.(type) {
	case *ast.Ident:
		return v.Name
	case *ast.StarExpr:
		return "*" + typeString(v.X)
	case *ast.ArrayType:
		return "[]" + typeString(v.Elt)
	case *ast.MapType:
		return "map[" + typeString(v.Key) + "]" + typeString(v.Value)
	case *ast.SelectorExpr:
		return typeString(v.X) + "." + v.Sel.Name
	}
	return "unknown"
}

func resetField(recv, name, tp string) string {
	switch {
	case strings.HasPrefix(tp, "int") || strings.HasPrefix(tp, "uint") || strings.HasPrefix(tp, "float"):
		return "0"
	case tp == "string":
		return `""`
	case strings.HasPrefix(tp, "[]"):
		return recv + "." + name + "[:0]"
	case strings.HasPrefix(tp, "map["):
		return "nil"
	case strings.HasPrefix(tp, "*"):
		return "nil"
	case tp == "bool":
		return "false"
	default:
		return "nil"
	}
}

type Resetter interface {
	Reset()
}

// Pool - обобщенный пул для объектов с Reset()
type Pool[T Resetter] struct {
	pool sync.Pool
}

// New создает новый Pool
func New[T Resetter]() *Pool[T] {
	return &Pool[T]{}
}

// Get возвращает объект из пула (или создает новый)
func (p *Pool[T]) Get() *T {
	if obj := p.pool.Get(); obj != nil {
		return obj.(*T)
	}
	return new(T)
}

// Put возвращает объект в пул с вызовом Reset()
func (p *Pool[T]) Put(obj T) {
	obj.Reset()
	p.pool.Put(obj)
}
